### ISSUE TITLE
Test basic install of IRAF

### ISSUE THREAD

**Issue by steelewool** [steelewool/iraf#1]

**Comment by zcsteele** [comment]
I was able to install IRAF on my desktop (64-bit linux) using the `./install` script, using the default values for all paths.

The installer is hardwired to update the user's shell login to call a c-shell script.  I had to manually modify it to use a bash script (the installed copies both c-shell and bash versions of the script into `~/.iraf/`).

After running the bash setup script, I was able to execute `cl` without any obvious errors.

**Comment by RobSteele49** [comment]
You are ahead of me. Let's talk today to figure out what I'm doing wrong.

Dad

**Comment by RobSteele49** [comment]
So here is what I did today:
a) cloned a version of the software in my git directory (/home/steele/git) using the command:
 1968  git clone https://github.com/steelewool/iraf.git

b) Created the $iraf symbol using the command:
 1970  iraf=/home/steele/git/iraf
 1971  export iraf

c) Removed the directory /home/steele/.iraf which was leftover from previous installations:

d) Jumped into /home/steele/git/iraf and run ./install. This ran without any errors.

e) When I tried to execute ecl and cl I got problems because I was attempting to use the 'wrong' version. As illustrated by the which command.

$ which ecl
/usr/local/bin/ecl

This is an artifact of my attempt to run ./install with the system option.

f) Sourced the setup.cs with the command: source .iraf/setup.sh

I was then able to run ecl, cl, and iraf without any major issues.

I'm closing this issue as it is not time to try recompile and retest the code.
